mod bitboard;
mod board;
mod color;
mod fen;
mod file;
mod lookup_tables;
mod move_type;
mod movegen;
mod piece;
mod player;
mod position;
mod quadrant;
mod rank;
mod role;
mod square;

pub use bitboard::Bitboard;
pub use board::Board;
pub use color::Color;
pub use fen::Fen;
pub use file::File;
pub use lookup_tables::LookupTables;
pub use move_type::Move;
pub use piece::Piece;
pub use player::Player;
pub use position::{Position, PositionError};
pub use quadrant::Quadrant;
pub use rank::Rank;
pub use role::Role;
pub use square::Square;

pub const BOARD_WIDTH: usize = 16;
pub const BOARD_SIZE: usize = BOARD_WIDTH * BOARD_WIDTH;
